// Generated by CoffeeScript 1.7.1
(function() {
  var en;

  en = {
    firstname: "First name",
    lastname: "Last name",
    localization: "Language",
    langenglish: "English",
    langfrench: "French",
    username: "Username"
  };

  T9n.map("en", en);

}).call(this);
