// Generated by CoffeeScript 1.7.1
(function() {
  var fr;

  fr = {
    firstname: "Prénom",
    lastname: "Nom",
    localization: "Langue",
    langenglish: "Anglais",
    langfrench: "Français"
  };

  T9n.map("fr", fr);

}).call(this);
